spring.application.name=DevWeb2
spring.profiles.active=dev


# Define o perfil padrão ao rodar SEM especificar nenhum
spring.mvc.problemdetails.enabled=true

# Você pode trocar em runtime com:
#   --spring.profiles.active=test
#   --spring.profiles.active=dev
